In [1]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [5]:
df1 = pd.read_csv("~/Downloads/noaa-daily-weather-data.csv", sep=";")
df1["NEW_DATE"] = pd.to_datetime(df1.DATE)
df1

,GHCN_DIN,DATE,PRCP,SNOW,TMAX,TMIN,ELEVATION,NAME,COORD,COUNTRY_CODE,NEW_DATE
0,USW00093738,2015-02-05,0.0,0.0,5.0,-8.2,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2015-02-05
1,USW00093738,2015-03-02,0.0,0.0,5.0,-2.7,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2015-03-02
2,USW00093738,2015-03-17,0.0,0.0,20.6,2.2,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2015-03-17
3,USW00093738,2015-04-12,0.0,0.0,20.6,0.0,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2015-04-12
4,USW00093738,2015-04-15,0.0,0.0,18.3,6.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2015-04-15
...,...,...,...,...,...,...,...,...,...,...,...
2032,USW00093738,2020-04-11,0.0,0.0,17.2,1.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2020-04-11
2033,USW00093738,2020-04-19,0.0,0.0,18.3,-1.0,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2020-04-19
2034,USW00093738,2020-05-26,0.0,0.0,27.2,12.8,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2020-05-26
2035,USW00093738,2020-06-15,0.0,0.0,24.4,14.4,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2020-06-15
2036,USW00093738,2020-07-04,0.0,0.0,33.9,21.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US,2020-07-04

In [18]:
accidents = pd.read_csv("df_final.csv")
accidents["NEW_DATE"] = pd.to_datetime(accidents.Time)
#accidents = accidents.set_index("NEW_DATE")
accidents

,Unnamed: 0,Time,Name,Severity,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,...,Lighting,Temperature,Wind_Chill,Humidity,Pressure,Visibility,Wind_Speed,Precipitation,Wind_Direction,Weather_Condition
NEW_DATE,,,,,,,,,,,,,,,,,,,,,
2020-09-17 00:00:00,0,2020-09-17 00:00:00,"(Interval(38.791000000000004, 38.844, closed='...",2,0,0,0,0,0,0,...,"(17, 21]",1.038835,0.915858,1.650485,0.779256,0.250809,0.213592,0.0,S,Cloudy
2020-09-17 04:00:00,1,2020-09-17 04:00:00,"(Interval(38.791000000000004, 38.844, closed='...",0,0,0,0,0,0,0,...,"(17, 21]",1.038835,0.915858,1.650485,0.779256,0.250809,0.213592,0.0,S,Cloudy
2020-09-17 08:00:00,2,2020-09-17 08:00:00,"(Interval(38.791000000000004, 38.844, closed='...",0,0,0,0,0,0,0,...,"(17, 21]",1.038835,0.915858,1.650485,0.779256,0.250809,0.213592,0.0,S,Cloudy
2020-09-17 12:00:00,3,2020-09-17 12:00:00,"(Interval(38.791000000000004, 38.844, closed='...",0,0,0,0,0,0,0,...,"(17, 21]",1.038835,0.915858,1.650485,0.779256,0.250809,0.213592,0.0,S,Cloudy
2020-09-17 16:00:00,4,2020-09-17 16:00:00,"(Interval(38.791000000000004, 38.844, closed='...",0,0,0,0,0,0,0,...,"(17, 21]",1.038835,0.915858,1.650485,0.779256,0.250809,0.213592,0.0,S,Cloudy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-01-15 04:00:00,2371618,2019-01-15 04:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,1,0,1,0,0,0,...,"(4, 9]",0.017225,0.006462,0.025422,0.014298,0.004752,0.004657,0.0,NW,Clear
2019-01-15 08:00:00,2371619,2019-01-15 08:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,1,0,1,0,0,0,...,"(4, 9]",0.017225,0.006462,0.025422,0.014298,0.004752,0.004657,0.0,NW,Clear
2019-01-15 12:00:00,2371620,2019-01-15 12:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,1,0,1,0,0,0,...,"(4, 9]",0.017225,0.006462,0.025422,0.014298,0.004752,0.004657,0.0,NW,Clear
2019-01-15 16:00:00,2371621,2019-01-15 16:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",2,1,0,1,0,0,0,...,"(4, 9]",0.017225,0.006462,0.025422,0.014298,0.004752,0.004657,0.0,NW,Clear
2020-02-13 12:00:00,2371622,2020-02-13 12:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",2,0,0,1,0,0,0,...,"(9, 17]",54.000000,54.000000,79.000000,29.630000,10.000000,0.000000,0.0,CALM,Cloudy

In [16]:
#df1 = df1.set_index("NEW_DATE")
#df1 = df1.resample("240min").ffill()
df1

,GHCN_DIN,PRCP,SNOW,TMAX,TMIN,ELEVATION,NAME,COORD,COUNTRY_CODE
NEW_DATE,,,,,,,,,
2015-01-01 00:00:00,USW00093738,0.0,0.0,5.6,-7.7,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2015-01-01 04:00:00,USW00093738,0.0,0.0,5.6,-7.7,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2015-01-01 08:00:00,USW00093738,0.0,0.0,5.6,-7.7,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2015-01-01 12:00:00,USW00093738,0.0,0.0,5.6,-7.7,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2015-01-01 16:00:00,USW00093738,0.0,0.0,5.6,-7.7,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
...,...,...,...,...,...,...,...,...,...
2020-07-28 08:00:00,USW00093738,0.0,0.0,33.3,22.8,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-28 12:00:00,USW00093738,0.0,0.0,33.3,22.8,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-28 16:00:00,USW00093738,0.0,0.0,33.3,22.8,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-28 20:00:00,USW00093738,0.0,0.0,33.3,22.8,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-29 00:00:00,USW00093738,0.0,0.0,33.3,21.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US

In [23]:
df1_final = accidents.merge(df1,how="inner",left_index=True, right_index=True)
df1_final.columns

Index(['Unnamed: 0', 'Time', 'Name', 'Severity', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop', 'Lighting',
       'Temperature', 'Wind_Chill', 'Humidity', 'Pressure', 'Visibility',
       'Wind_Speed', 'Precipitation', 'Wind_Direction', 'Weather_Condition',
       'GHCN_DIN', 'PRCP', 'SNOW', 'TMAX', 'TMIN', 'ELEVATION', 'NAME',
       'COORD', 'COUNTRY_CODE'],
      dtype='object')

In [24]:
df1_final = df1_final[['Time', 'Name', 'Severity', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop', 'Lighting', 'GHCN_DIN', 'PRCP', 'SNOW', 'TMAX', 'TMIN', 'ELEVATION', 'NAME',
       'COORD', 'COUNTRY_CODE']]
df1_final

,Time,Name,Severity,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,...,Lighting,GHCN_DIN,PRCP,SNOW,TMAX,TMIN,ELEVATION,NAME,COORD,COUNTRY_CODE
NEW_DATE,,,,,,,,,,,,,,,,,,,,,
2016-06-21 08:00:00,2016-06-21 08:00:00,"(Interval(38.91, 38.914, closed='right'), Inte...",4,0,0,0,0,0,0,0,...,"(4, 9]",USW00093738,429.0,0.0,30.6,20.0,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2016-06-21 12:00:00,2016-06-21 12:00:00,"(Interval(38.888, 38.892, closed='right'), Int...",4,0,0,1,0,0,0,0,...,"(9, 17]",USW00093738,429.0,0.0,30.6,20.0,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2016-06-21 12:00:00,2016-06-21 12:00:00,"(Interval(38.888, 38.892, closed='right'), Int...",4,1,0,1,0,0,0,0,...,"(9, 17]",USW00093738,429.0,0.0,30.6,20.0,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2016-06-21 12:00:00,2016-06-21 12:00:00,"(Interval(38.91, 38.914, closed='right'), Inte...",0,0,0,0,0,0,0,0,...,"(4, 9]",USW00093738,429.0,0.0,30.6,20.0,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2016-06-21 16:00:00,2016-06-21 16:00:00,"(Interval(38.866, 38.872, closed='right'), Int...",2,0,0,1,0,1,0,0,...,"(4.0, 9.0]",USW00093738,429.0,0.0,30.6,20.0,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-29 00:00:00,2020-07-29 00:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,1,0,1,0,0,0,0,...,"(9, 17]",USW00093738,0.0,0.0,33.3,21.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-29 00:00:00,2020-07-29 00:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,0,0,0,0,0,0,0,...,"(4, 9]",USW00093738,0.0,0.0,33.3,21.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-29 00:00:00,2020-07-29 00:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,1,0,0,0,0,0,0,...,"(4.0, 9.0]",USW00093738,0.0,0.0,33.3,21.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-29 00:00:00,2020-07-29 00:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,1,0,0,0,0,0,0,...,"(9.0, 17.0]",USW00093738,0.0,0.0,33.3,21.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US
2020-07-29 00:00:00,2020-07-29 00:00:00,"(Interval(38.953, 38.992, closed='right'), Int...",0,0,0,1,0,0,0,0,...,"(9, 17]",USW00093738,0.0,0.0,33.3,21.1,88.4,WASHINGTON DC DULLES AP,"38.9408,-77.4636",US

In [26]:
df1_final.to_csv("df1_really_final.csv")